// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk-sOt-sdT5fbcco6WNZsgoBkS13aEA20',
    appId: '1:130059566389:web:87a5ef0d491433df87207c',
    messagingSenderId: '130059566389',
    projectId: 'social-media-app-625f2',
    authDomain: 'social-media-app-625f2.firebaseapp.com',
    storageBucket: 'social-media-app-625f2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADAbiPUh6_Xg3r1hXKpFgXnVt4-ovDgMQ',
    appId: '1:130059566389:android:67a6a87fb202e76f87207c',
    messagingSenderId: '130059566389',
    projectId: 'social-media-app-625f2',
    storageBucket: 'social-media-app-625f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOl7B617G0cAICFtU3QriMlApjELWYfCo',
    appId: '1:130059566389:ios:98b589fa93fc167687207c',
    messagingSenderId: '130059566389',
    projectId: 'social-media-app-625f2',
    storageBucket: 'social-media-app-625f2.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOl7B617G0cAICFtU3QriMlApjELWYfCo',
    appId: '1:130059566389:ios:98b589fa93fc167687207c',
    messagingSenderId: '130059566389',
    projectId: 'social-media-app-625f2',
    storageBucket: 'social-media-app-625f2.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk-sOt-sdT5fbcco6WNZsgoBkS13aEA20',
    appId: '1:130059566389:web:9f0911456ce08dac87207c',
    messagingSenderId: '130059566389',
    projectId: 'social-media-app-625f2',
    authDomain: 'social-media-app-625f2.firebaseapp.com',
    storageBucket: 'social-media-app-625f2.appspot.com',
  );
}
